export const metadata={title:"Qui sommes-nous ?",description:"La société Tardy, spécialiste du boyau naturel depuis 1894.",alternates:{canonical:"/qui-sommes-nous/"}};
export default function Page(){return <main>
<section className="pageHero"><div className="shell"><div className="breadcrumbs"><a href="/">Accueil</a><span>·</span><span>Qui sommes-nous ?</span></div><div className="pageHeroGrid"><div><div className="eyebrow">Société Tardy</div><h1>Spécialiste du boyau naturel depuis 1894.</h1></div><p>Une maison marseillaise historique dont le métier est de sélectionner, transformer et commercialiser des boyaux naturels pour les professionnels.</p></div></div></section>
<section className="section heritageNarrativeSection"><div className="shell heritageNarrative">
<article className="heritageChapter"><figure><img src="/assets/Downloader.la-621786f021532.jpg" alt="Société Tardy"/></figure><div className="heritageChapterCopy"><div className="eyebrow">Présentation</div><h2>Plus d’un siècle de savoir-faire.</h2><p>La société Tardy, constituée en 1894, a pour vocation de sélectionner, transformer et commercialiser des boyaux naturels à destination de grossistes, charcutiers et salaisonniers.</p></div></article>
<article className="heritageChapter"><figure><img src="/assets/home-original/histoire.webp" alt="Archive et histoire de la maison Tardy"/></figure><div className="heritageChapterCopy"><p>Notre expérience nous a permis d’acquérir un savoir-faire important quant au choix des boyaux ainsi qu’à leurs préparations et leurs conditionnements pour une qualité optimale.</p></div></article>
<article className="heritageChapter heritageQuoteChapter"><figure><img src="/assets/home-original/fabrication.jpg" alt="Fabrication et savoir-faire Tardy"/></figure><div className="heritageChapterCopy"><blockquote>« En apportant le meilleur soin à toute notre gamme de boyaux naturels, nous espérons contribuer activement à la qualité des produits de charcuterie. »</blockquote><p><strong>M. Jean TARDY / Fondateur</strong></p></div></article>
</div></section>
<section className="section heritageQualityLedger"><div className="shell"><div className="heritageQualityRow"><span>01</span><h2>Meilleures provenances</h2><p>Matière origine de qualité<br/>Standardisation des produits</p></div><div className="heritageQualityRow"><span>02</span><h2>Service de Livraison</h2><p>Livraison dans toute la France de 24h à 48h<br/>Transport par la STEF</p></div><div className="heritageQualityRow"><span>03</span><h2>Traçabilité garantie</h2><p>Contrôle qualité et analyse bactériologique</p></div></div></section><section className="heritageContact"><div className="shell heritageContactInner"><span className="heritageContactYear" aria-hidden="true">1894</span><div><h2>À votre service depuis 1894.</h2></div><div className="heritageContactAside"><p>Nous sommes à votre disposition pour répondre à vos besoins en boyaux naturels.</p><a href="/contactez-nous/" className="heritageContactLink"><span>Contactez-nous</span><i>↗</i></a></div></div></section>
</main>}
