import AnimalMap from "../../components/AnimalMap";
import LegacyQuality from "../../components/LegacyQuality";
const products=[
{title:"Menus de boeuf",href:"/nos-produits/boyaux-de-boeuf/menu-de-boeuf/",intro:"Le menu de bœuf correspond à l’intestin grêle. Il est de texture plus épaisse que le menu de porc.",rows:[["Présentation","Il est vendu en paquet de 15 ou 18 mètres"],["Calibre","38/40 – 40/43 – 43/46 – 46/+ – 50/+"],["Conditionnement","Fûts et seaux"],["Utilisation","Boudin, Cervelas, Andouillette, Chorizo, Soubressade, Saucisson de foie…"]]},
{title:"Gros de Bœuf",href:"/nos-produits/boyaux-de-boeuf/gros-de-boeuf/",intro:"Le gros de bœuf (ou droit de bœuf) correspond au colon.",rows:[["Présentation","Il est présenté en paquets de 9 mètres ou en bouts coupés attachés et dégraissés"],["Calibre","45/50 – 50/55, 55/60, 60/65, 65/70"],["Conditionnement","En fûts ou en seaux."],["Utilisation","Saucissons d’Arles, Saucissons à cuire, Saucisson sec, Chorizo, Cervelas de Lyon, Soubressade…"]]},
{title:"Baudruche de Bœuf",href:"/nos-produits/boyaux-de-boeuf/baudruche-de-boeuf/",intro:"La baudruche de bœuf correspond au coecum.",rows:[["Présentation","Conditionnée en paquet de 5."],["Calibre","90/100 – 100/110 – 120/130 – 130/150 – 150/+"],["Utilisation","Elle sert à la fabrication d’Andouilles (Guéménée et Vire), de Galabard (boudin froid), de Mortadelle, de Coppa, de Salami, de Langue Ecarlate…"]]}
];
export const metadata={title:"Boyaux de bœuf",alternates:{canonical:"/nos-produits/boyaux-de-boeuf/"}};
export default function Page(){return <main>
<section className="pageHero"><div className="shell"><div className="breadcrumbs"><a href="/">Accueil</a><span>·</span><a href="/nos-produits/">Boyaux naturels</a><span>·</span><span>Bœuf</span></div><div className="pageHeroGrid"><div><div className="eyebrow">Boyaux de Boeuf</div><h1>Nos boyaux de Bœuf</h1></div></div></div></section>
<section className="section"><div className="shell animalGrid"><div className="animalIntro"><div className="eyebrow">Navigation anatomique</div><h2>Nos boyaux de Bœuf</h2><div className="animalLinks">{products.map(p=><a href={p.href} key={p.title}><span>{p.title}</span><span>↗</span></a>)}</div></div><AnimalMap kind="boeuf"/></div></section>
<section className="section pale"><div className="shell"><div className="technicalCatalog">{products.map((p,i)=><article className="technicalEntry" key={p.title}><div className="technicalNumber">{String(i+1).padStart(2,"0")}</div><div className="technicalMain"><a href={p.href}><h2>{p.title}</h2></a><p>{p.intro}</p></div><dl className="technicalSpecs">{p.rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></article>)}</div></div></section>
<LegacyQuality/>
</main>}