import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://casing-tardy.com"),
  title: { default: "Casing Tardy — Boyaux, épices, marinades & emballages", template: "%s | Casing Tardy" },
  description: "Casing Tardy accompagne les professionnels de la charcuterie depuis 1894 : boyaux naturels, épices, marinades et solutions de conditionnement.",
  openGraph: { type:"website", locale:"fr_FR", siteName:"Casing Tardy", title:"Casing Tardy — L'expertise charcutière depuis 1894", description:"Boyaux naturels, épices, marinades et emballages pour les professionnels." },
  robots: { index:true, follow:true },
};
export default function RootLayout({children}:{children:React.ReactNode}) {
  const jsonLd={"@context":"https://schema.org","@type":"Organization","name":"Casing Tardy","url":"https://casing-tardy.com","foundingDate":"1894","areaServed":"FR","description":"Fournisseur professionnel de boyaux naturels, épices, marinades et emballages pour la charcuterie."};
  return <html lang="fr"><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><div className="siteTop"><span><b>Tardy</b> · Maison fondée en 1894</span><span>Marseille · France · Fournisseur des professionnels</span></div><Header/>{children}<Footer/></body></html>
}
function Header(){return <header className="header"><a className="brandMark" href="/"><span className="brandSeal">1894</span><span className="brand">TARDY<span>BOYAUDERIE</span></span></a><nav className="nav"><details><summary>Boyaux naturels</summary><div className="mega"><a href="/nos-produits/boyaux-de-porc/"><b>Porc</b><br/>Menus, chaudins, sacs, suivants, rosettes</a><a href="/nos-produits/boyaux-de-mouton/"><b>Mouton</b><br/>Calibres et qualités professionnelles</a><a href="/nos-produits/boyaux-de-boeuf/"><b>Bœuf</b><br/>Menus, gros et baudruches</a></div></details><details><summary>Épices & préparation</summary><div className="mega"><a href="/les-mixs-complets/"><b>Mixs complets</b><br/>Recettes professionnelles</a><a href="/epices-naturelles/"><b>Épices naturelles</b><br/>Sélection d'épices</a><a href="/les-chapelures/"><b>Chapelures</b><br/>Panures et préparations</a></div></details><a href="/nos-produits/marinades/">Marinades</a><a href="/nos-produits/emballages-sacs/">Emballages</a></nav><div className="headerActions"><a className="button ghost" href="/nos-produits/">Catalogue</a><a className="navCta" href="/contactez-nous/">Contact ↗</a></div></header>}
function Footer(){return <footer><div><div className="brandMark"><span className="brandSeal">1894</span><span className="brand">TARDY<span>BOYAUDERIE</span></span></div><p>Boyaux naturels, épices, marinades et solutions de conditionnement pour les professionnels de la charcuterie.</p></div><div><strong>Produits</strong><a href="/nos-produits/boyaux-de-porc/">Boyaux de porc</a><a href="/nos-produits/boyaux-de-mouton/">Boyaux de mouton</a><a href="/nos-produits/boyaux-de-boeuf/">Boyaux de bœuf</a><a href="/les-mixs-complets/">Épices & mixs</a><a href="/nos-produits/marinades/">Marinades</a></div><div><strong>Entreprise</strong><a href="/contactez-nous/">Contact</a><a href="/nos-produits/">Catalogue complet</a><a href="/robots.txt">Robots</a><a href="/sitemap.xml">Sitemap</a></div></footer>}
