export const metadata={title:"Nos produits",description:"Catalogue professionnel Casing Tardy : boyaux naturels, épices, marinades et emballages.",alternates:{canonical:"/nos-produits/"}};
const items=[
["Boyaux de porc","Menus, chaudins, sacs, suivants, rosettes et fuseaux.","/nos-produits/boyaux-de-porc/","/assets/porc.png","Boyaux naturels","wide"],
["Boyaux de mouton","Menus de mouton, calibres et qualités professionnelles.","/nos-produits/boyaux-de-mouton/","/assets/mouton.png","Boyaux naturels",""],
["Boyaux de bœuf","Menus, gros de bœuf et baudruches.","/nos-produits/boyaux-de-boeuf/","/assets/boeuf.png","Boyaux naturels",""],
["Mixs & épices","Préparations complètes, épices naturelles et chapelures.","/epices/","/assets/epices-composees.png","Préparations","wide"],
["Marinades","Une large gamme de profils aromatiques pour vos recettes.","/nos-produits/marinades/","/assets/marinade-citronnelle.png","Saveurs",""],
["Emballages","Sacs sous vide et solutions de conditionnement.","/nos-produits/emballages-sacs/","/assets/saucisse-villageoise.jpg","Conditionnement",""]
];
export default function Products(){return <main><section className="pageHero"><div className="shell"><div className="breadcrumbs"><a href="/">Accueil</a><span>·</span><span>Catalogue</span></div><div className="pageHeroGrid"><div><div className="eyebrow">Catalogue professionnel</div><h1>Des produits pensés pour l'atelier.</h1></div><p>Retrouvez les principales familles Casing Tardy. Chaque univers est organisé selon la logique métier : espèce, partie anatomique, type de préparation ou usage.</p></div></div></section><section className="section"><div className="shell"><div className="catalogGrid">{items.map(([t,d,l,img,k,w])=><a className={"catalogCard "+w} href={l} key={t}><div className={"catalogVisual "+(t==="Emballages"?"photo":"")}><img src={img} alt={t}/></div><div className="catalogBody"><small>{k}</small><h3>{t}</h3><p>{d}</p></div></a>)}</div></div></section></main>}