import LegacyQuality from "../../components/LegacyQuality";
export const metadata={title:"Boyaux manufacturés",alternates:{canonical:"/nos-produits/boyaux-manufactures/"}};
export default function Page(){return <main>
<section className="pageHero"><div className="shell"><div className="breadcrumbs"><a href="/">Accueil</a><span>·</span><a href="/nos-produits/">Nos produits</a><span>·</span><span>Boyaux manufacturés</span></div><div className="pageHeroGrid"><div><div className="eyebrow">Gamme technique</div><h1>Nos boyaux manufacturés</h1></div><p>Les boyaux manufacturés sont fabriqués à partir de menus de porc fendus. Ces menus ouverts sont superposés sur des matrices dont les diamètres correspondent à différents calibres.</p></div></div></section>
<section className="section manufacturedPrinciple"><div className="shell"><div className="eyebrow">Principe</div><h2>Une enveloppe mise en forme pour répondre à un calibre et à une géométrie précis.</h2><p>Les boyaux manufacturés partent de menus ouverts puis superposés sur des matrices. Cette illustration montre leur usage final au moment du poussage, et non un produit Tardy photographié.</p></div></section>
<section className="section pale"><div className="shell manufacturedIndexFlow">
<article className="manufacturedFlowRow"><span>01</span><div className="manufacturedFlowCopy"><small>Fuseaux</small><h2>Forme conique type rosette</h2><p>7/9.5/35 · 8/10/33 · 8/10/35 · 8.5/12.5/55 · 9.5/14.5/55 · 10/15/60 · 12/16.5/60 · 13/17/65<br/>Liste non exhaustive.</p></div><figure><img src="/assets/editorial-external/hog-casings-salt.webp" alt="Boyaux naturels conservés au sel, illustration"/><figcaption>Matière brute — illustration.</figcaption></figure></article>
<article className="manufacturedFlowRow"><span>02</span><div className="manufacturedFlowCopy"><small>Cylindriques</small><h2>Poches simples</h2><p>8/25 · 9/40 · 10/40 · 10/50 · 11/35 · 11/40 · 11/45 · 11/50 · 12/50 · 13/50 · 14/50 · 15/50 · 16/50 · 17/50 · 26/50<br/>Liste non exhaustive.</p></div><figure><img src="/assets/editorial-external/sausage-making.webp" alt="Mise en œuvre d’un boyau lors de la fabrication de saucisses, illustration"/><figcaption>Illustration d’usage — mise en œuvre d’un boyau lors du poussage.</figcaption></figure></article>
<article className="manufacturedFlowRow noVisual"><span>03</span><div className="manufacturedFlowCopy"><small>Feuilles (mouchoirs):</small><h2>Mouchoirs</h2><p>50/50 · 50/70 · 50/85<br/>Liste non exhaustive.</p></div></article>
</div></section>
<LegacyQuality/>
</main>}
