import EpicenouBrand from "../components/EpicenouBrand";
import LegacyQuality from "../components/LegacyQuality";
const refs=["Persil","Herbes de Provence","Poivre blanc moulu","Poivre concassé","Piment de Cayenne","Paprika","Piment doux","Fenouille moulu","Curry","Cumin en poudre","Colombo","Ail en poudre","Ail en granule","Muscade moulue","Oignons granule","Oignons frits","Oignons en lanières","Échalote en poudre","Gingembre en poudre"];
export const metadata={title:"Épices naturelles",alternates:{canonical:"/epices-naturelles/"}};
export default function Page(){return <main>
<section className="pageHero"><div className="shell"><div className="breadcrumbs"><a href="/">Accueil</a><span>·</span><a href="/epices-epicenou/">Épices</a><span>·</span><span>Naturelles</span></div><div className="pageHeroGrid"><div><h1>Épices naturelles</h1></div><p><strong>Toutes nos épices sont vendues en sacs de 1 kg.</strong></p></div></div></section>
<EpicenouBrand compact/>
<section className="section"><div className="shell spiceEditorial"><div className="spiceMosaic"><figure className="spiceMosaicMain"><img src="/assets/poivre-concasse.png" alt="Poivre concassé"/><figcaption>Poivre concassé</figcaption></figure><figure><img src="/assets/epicenou/herbes-de-provence.webp" alt="Herbes de Provence"/><figcaption>Herbes de Provence</figcaption></figure><figure><img src="/assets/epicenou/piment-doux.webp" alt="Piment doux"/><figcaption>Piment doux</figcaption></figure><figure><img src="/assets/epicenou/ail-en-poudre.webp" alt="Ail en poudre"/><figcaption>Ail en poudre</figcaption></figure></div><div className="spiceList"><div className="eyebrow">19 références</div>{refs.map((x,i)=><div className="spiceListItem" key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div></div></section>
<LegacyQuality/>
</main>}